Update

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -42,7 +42,7 @@ jobs:
         if: github.event_name == 'schedule'
         id: get-versions
         run: |
-          echo LLVM_VERSION=$(git ls-remote https://github.com/llvm/llvm-project.git | grep 'refs/heads/main$' | awk '{print $1}') >> $GITHUB_OUTPUT
+          echo LLVM_VERSION=17.0.1 >> $GITHUB_OUTPUT
           echo MINGW_W64_VERSION=$(git ls-remote https://github.com/mingw-w64/mingw-w64.git | grep 'refs/heads/master$' | awk '{print $1}') >> $GITHUB_OUTPUT
           echo PYTHON_VERSION_MINGW=$(git ls-remote https://github.com/msys2-contrib/cpython-mingw.git | grep 'refs/heads/mingw-v3.10.11$' | awk '{print $1}') >> $GITHUB_OUTPUT
           cat $GITHUB_OUTPUT
@@ -87,50 +87,50 @@ jobs:
 
   # Crosscompile the toolchain for running on Linux on a different architecture, bundle the runtime
   # libraries that were built in the 'linux' step above.
-  linux-cross-aarch64:
-    if: (github.event_name != 'schedule') || (github.repository == 'mstorsjo/llvm-mingw')
-    needs: [linux, prepare]
-    runs-on: ubuntu-20.04
-    steps:
-      - uses: actions/checkout@v3
-      - name: Build
-        env:
-          LLVM_VERSION: ${{needs.prepare.outputs.LLVM_VERSION}}
-          MINGW_W64_VERSION: ${{needs.prepare.outputs.MINGW_W64_VERSION}}
-        run: |
-          sudo apt-get update && sudo apt-get install ninja-build g++-aarch64-linux-gnu
-          ./build-all.sh $(pwd)/install/llvm-mingw --disable-clang-tools-extra --no-runtimes --host=aarch64-linux-gnu
-          .github/workflows/store-version.sh install/llvm-mingw/versions.txt
-      - uses: actions/download-artifact@v3
-        with:
-          name: linux-ucrt-x86_64-toolchain
-      - name: Unpack native toolchain
-        run: |
-          tar -Jxf llvm-mingw-*.tar.xz
-          rm llvm-mingw-*.tar.xz
-          mv llvm-mingw* llvm-mingw-native
-      - name: Assemble the cross-built toolchain
-        run: |
-          ./prepare-cross-toolchain-unix.sh $(pwd)/llvm-mingw-native $(pwd)/install/llvm-mingw
-      - name: Test using the cross-built assembled toolchain
-        run: |
-          sudo apt-get update && sudo apt-get install qemu-user-static libc6-arm64-cross libstdc++6-arm64-cross
-          QEMU_LD_PREFIX=/usr/aarch64-linux-gnu RUN_I686=false RUN_X86_64=false ./run-tests.sh $(pwd)/install/llvm-mingw
-      - name: Package the toolchain
-        env:
-          TAG: ${{needs.prepare.outputs.TAG}}
-        run: |
-          cd install
-          DISTRO=ubuntu-$(grep DISTRIB_RELEASE /etc/lsb-release | cut -f 2 -d =)-aarch64
-          NAME=llvm-mingw-$TAG-ucrt-$DISTRO
-          mv llvm-mingw $NAME
-          tar -Jcf ../$NAME.tar.xz $NAME
-      - uses: actions/upload-artifact@v3
-        with:
-          name: linux-ucrt-aarch64-toolchain
-          path: |
-            llvm-mingw-*.tar.xz
-          retention-days: 7
+  # linux-cross-aarch64:
+  #   if: (github.event_name != 'schedule') || (github.repository == 'mstorsjo/llvm-mingw')
+  #   needs: [linux, prepare]
+  #   runs-on: ubuntu-20.04
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - name: Build
+  #       env:
+  #         LLVM_VERSION: ${{needs.prepare.outputs.LLVM_VERSION}}
+  #         MINGW_W64_VERSION: ${{needs.prepare.outputs.MINGW_W64_VERSION}}
+  #       run: |
+  #         sudo apt-get update && sudo apt-get install ninja-build g++-aarch64-linux-gnu
+  #         ./build-all.sh $(pwd)/install/llvm-mingw --disable-clang-tools-extra --no-runtimes --host=aarch64-linux-gnu
+  #         .github/workflows/store-version.sh install/llvm-mingw/versions.txt
+  #     - uses: actions/download-artifact@v3
+  #       with:
+  #         name: linux-ucrt-x86_64-toolchain
+  #     - name: Unpack native toolchain
+  #       run: |
+  #         tar -Jxf llvm-mingw-*.tar.xz
+  #         rm llvm-mingw-*.tar.xz
+  #         mv llvm-mingw* llvm-mingw-native
+  #     - name: Assemble the cross-built toolchain
+  #       run: |
+  #         ./prepare-cross-toolchain-unix.sh $(pwd)/llvm-mingw-native $(pwd)/install/llvm-mingw
+  #     - name: Test using the cross-built assembled toolchain
+  #       run: |
+  #         sudo apt-get update && sudo apt-get install qemu-user-static libc6-arm64-cross libstdc++6-arm64-cross
+  #         QEMU_LD_PREFIX=/usr/aarch64-linux-gnu RUN_I686=false RUN_X86_64=false ./run-tests.sh $(pwd)/install/llvm-mingw
+  #     - name: Package the toolchain
+  #       env:
+  #         TAG: ${{needs.prepare.outputs.TAG}}
+  #       run: |
+  #         cd install
+  #         DISTRO=ubuntu-$(grep DISTRIB_RELEASE /etc/lsb-release | cut -f 2 -d =)-aarch64
+  #         NAME=llvm-mingw-$TAG-ucrt-$DISTRO
+  #         mv llvm-mingw $NAME
+  #         tar -Jcf ../$NAME.tar.xz $NAME
+  #     - uses: actions/upload-artifact@v3
+  #       with:
+  #         name: linux-ucrt-aarch64-toolchain
+  #         path: |
+  #           llvm-mingw-*.tar.xz
+  #         retention-days: 7
 
   # Build a cross compiler for Linux, targeting Windows, with assertions enabled.
   #
@@ -166,36 +166,36 @@ jobs:
           retention-days: 7
 
   # Build a cross compiler for macOS, targeting Windows.
-  macos:
-    if: (github.event_name != 'schedule') || (github.repository == 'mstorsjo/llvm-mingw')
-    needs: [prepare]
-    runs-on: macos-latest
-    steps:
-      - uses: actions/checkout@v3
-      - name: Build
-        env:
-          LLVM_VERSION: ${{needs.prepare.outputs.LLVM_VERSION}}
-          MINGW_W64_VERSION: ${{needs.prepare.outputs.MINGW_W64_VERSION}}
-          TAG: ${{needs.prepare.outputs.TAG}}
-        run: |
-          brew install ninja
-          # Disable zstd and python. Both are available on the runners, but
-          # installed with homebrew, and only available in the native (x86_64)
-          # form. Therefore, autodetection will pick them up, but linking
-          # universal binaries fails as those libraries are unavailable in the
-          # other (arm64) architecture form.
-          MACOS_REDIST=1 LLVM_CMAKEFLAGS="-DLLVM_ENABLE_ZSTD=OFF -DLLDB_ENABLE_PYTHON=OFF" ./build-all.sh $(pwd)/install/llvm-mingw --disable-clang-tools-extra
-          .github/workflows/store-version.sh install/llvm-mingw/versions.txt
-          cd install
-          NAME=llvm-mingw-$TAG-ucrt-macos-universal
-          mv llvm-mingw $NAME
-          tar -Jcf ../$NAME.tar.xz $NAME
-      - uses: actions/upload-artifact@v3
-        with:
-          name: macos-ucrt-toolchain
-          path: |
-            llvm-mingw-*.tar.xz
-          retention-days: 7
+  # macos:
+  #   if: (github.event_name != 'schedule') || (github.repository == 'mstorsjo/llvm-mingw')
+  #   needs: [prepare]
+  #   runs-on: macos-latest
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - name: Build
+  #       env:
+  #         LLVM_VERSION: ${{needs.prepare.outputs.LLVM_VERSION}}
+  #         MINGW_W64_VERSION: ${{needs.prepare.outputs.MINGW_W64_VERSION}}
+  #         TAG: ${{needs.prepare.outputs.TAG}}
+  #       run: |
+  #         brew install ninja
+  #         # Disable zstd and python. Both are available on the runners, but
+  #         # installed with homebrew, and only available in the native (x86_64)
+  #         # form. Therefore, autodetection will pick them up, but linking
+  #         # universal binaries fails as those libraries are unavailable in the
+  #         # other (arm64) architecture form.
+  #         MACOS_REDIST=1 LLVM_CMAKEFLAGS="-DLLVM_ENABLE_ZSTD=OFF -DLLDB_ENABLE_PYTHON=OFF" ./build-all.sh $(pwd)/install/llvm-mingw --disable-clang-tools-extra
+  #         .github/workflows/store-version.sh install/llvm-mingw/versions.txt
+  #         cd install
+  #         NAME=llvm-mingw-$TAG-ucrt-macos-universal
+  #         mv llvm-mingw $NAME
+  #         tar -Jcf ../$NAME.tar.xz $NAME
+  #     - uses: actions/upload-artifact@v3
+  #       with:
+  #         name: macos-ucrt-toolchain
+  #         path: |
+  #           llvm-mingw-*.tar.xz
+  #         retention-days: 7
 
   # Test building the toolchain on msys2 (in the mingw64 and clang64
   # environments). The binaries built here rely on the runtime libraries from
@@ -249,8 +249,8 @@ jobs:
         include:
           - { arch: i686, crt: ucrt }
           - { arch: x86_64, crt: ucrt }
-          - { arch: armv7, crt: ucrt }
-          - { arch: aarch64, crt: ucrt }
+          # - { arch: armv7, crt: ucrt }
+          # - { arch: aarch64, crt: ucrt }
     steps:
       - uses: actions/download-artifact@v3
         with:
@@ -627,7 +627,7 @@ jobs:
     if: (github.event_name == 'schedule') && (github.repository == 'mstorsjo/llvm-mingw')
     permissions:
       contents: write
-    needs: [linux, linux-cross-aarch64, macos, linux-cross-windows, test-toolchain, linux-test-cross-build-ffmpeg, test-ffmpeg]
+    needs: [linux, linux-cross-windows, test-toolchain, linux-test-cross-build-ffmpeg, test-ffmpeg]
     runs-on: ubuntu-latest
     steps:
       - name: Download all artifacts
